name: Fortify Security Scan
on:
  workflow_dispatch:
  push:
#    # Master or main branch that you want to trigger this workflow for
   branches:
  pull_request:
    # The branches below must be a subset of the branches above

jobs:
  Fortif-SAST:
    runs-on: self-hosted
    container:
      image: maven
    permissions: write-all
    env:
      APPLICATION: "${{ github.event.repository.name }}"
      VERSION: "${{ github.ref_name }}"

      # Requires GitHub Advanced Security
      PUBLISH_SECURITY_ALERTS: false

    steps:
      # Check out source code
      - name: Checkout repository
        uses: actions/checkout@v3


      - run: cd DamnVulnerableBank

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install zip
        run: |
          apt update
          apt install zip -y

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Set up Fortify ScanCentral Client
      - name: Download Fortify Clients
        uses: fortify-ps/github-action/setup@main
        with:
          sc-client: latest

      # Retrieve FCLI
      - name: Install FCLI
        run: |
          wget -qO- https://github.com/fortify/fcli/releases/download/v2.0.0/fcli-linux.tgz | tar zxf -


      # Check out source code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Run FoD SAST Scan
        uses: fortify/github-action/fod-sast-scan@v1
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
          FOD_RELEASE: "${{ github.event.repository.name }} [AG]:${{ github.ref_name }}"
          EXTRA_PACKAGE_OPTS: -oss
          DO_WAIT: true
          # DO_EXPORT: true